// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceDesk.Tickets.Infrastructure.Persistence;

#nullable disable

namespace ServiceDesk.Tickets.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TicketsDbContext))]
    [Migration("20260623181508_InitialTickets")]
    partial class InitialTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceDesk.Tickets.Domain.SlaPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("ResolutionMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_minutes");

                    b.Property<int>("ResponseMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("response_minutes");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_sla_policies");

                    b.HasIndex(new[] { "Priority" }, "ix_sla_policies_priority")
                        .HasDatabaseName("ix_sla_policies_priority");

                    b.ToTable("sla_policies", (string)null);
                });

            modelBuilder.Entity("ServiceDesk.Tickets.Domain.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department_name");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_name");

                    b.Property<DateTime?>("FirstResponseAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_response_at_utc");

                    b.Property<string>("InventoryCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("inventory_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_utc");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid?>("ReporterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_user_id");

                    b.Property<bool>("ResolutionBreached")
                        .HasColumnType("boolean")
                        .HasColumnName("resolution_breached");

                    b.Property<DateTime?>("ResolutionDueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolution_due_at_utc");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<bool>("ResponseBreached")
                        .HasColumnType("boolean")
                        .HasColumnName("response_breached");

                    b.Property<DateTime?>("ResponseDueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_due_at_utc");

                    b.Property<Guid?>("SlaPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("sla_policy_id");

                    b.Property<string>("Solution")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("solution");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Worker")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("worker");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex(new[] { "CreatedAtUtc" }, "ix_tickets_created_at")
                        .IsDescending()
                        .HasDatabaseName("ix_tickets_created_at_utc");

                    b.HasIndex(new[] { "CreatedByUserId" }, "ix_tickets_created_by")
                        .HasDatabaseName("ix_tickets_created_by_user_id");

                    b.HasIndex(new[] { "LegacyId" }, "ix_tickets_legacy_id")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_legacy_id")
                        .HasFilter("legacy_id IS NOT NULL");

                    b.HasIndex(new[] { "Priority" }, "ix_tickets_priority")
                        .HasDatabaseName("ix_tickets_priority");

                    b.HasIndex(new[] { "ReporterUserId" }, "ix_tickets_reporter")
                        .HasDatabaseName("ix_tickets_reporter_user_id");

                    b.HasIndex(new[] { "Status" }, "ix_tickets_status")
                        .HasDatabaseName("ix_tickets_status");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("ServiceDesk.Tickets.Domain.TicketRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<DateTime>("RatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at_utc");

                    b.Property<Guid?>("RaterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("rater_user_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_ticket_ratings");

                    b.HasIndex(new[] { "TicketId" }, "ix_ticket_ratings_ticket")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_ratings_ticket_id");

                    b.ToTable("ticket_ratings", (string)null);
                });

            modelBuilder.Entity("ServiceDesk.Tickets.Infrastructure.Persistence.CategoryReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ServiceDesk.Tickets.Infrastructure.Persistence.UserReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ServiceDesk.Tickets.Domain.Ticket", b =>
                {
                    b.OwnsMany("ServiceDesk.Tickets.Domain.TicketAssignee", "Assignees", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("AssignedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("assigned_at_utc");

                            b1.Property<Guid>("AssigneeUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("assignee_user_id");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("FullNameSnapshot")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("full_name_snapshot");

                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid")
                                .HasColumnName("ticket_id");

                            b1.Property<DateTime?>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at_utc");

                            b1.HasKey("Id")
                                .HasName("pk_ticket_assignees");

                            b1.HasIndex(new[] { "TicketId", "AssigneeUserId" }, "ix_ticket_assignees_ticket_user")
                                .IsUnique()
                                .HasDatabaseName("ix_ticket_assignees_ticket_id_assignee_user_id");

                            b1.ToTable("ticket_assignees", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TicketId")
                                .HasConstraintName("fk_ticket_assignees_tickets_ticket_id");
                        });

                    b.OwnsMany("ServiceDesk.Tickets.Domain.TicketAttachment", "Attachments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("CommentId")
                                .HasColumnType("uuid")
                                .HasColumnName("comment_id");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("content_type");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(260)
                                .HasColumnType("character varying(260)")
                                .HasColumnName("file_name");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("size_bytes");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("storage_key");

                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid")
                                .HasColumnName("ticket_id");

                            b1.Property<DateTime?>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at_utc");

                            b1.Property<Guid>("UploadedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("uploaded_by_user_id");

                            b1.HasKey("Id")
                                .HasName("pk_ticket_attachments");

                            b1.HasIndex(new[] { "TicketId" }, "ix_ticket_attachments_ticket")
                                .HasDatabaseName("ix_ticket_attachments_ticket_id");

                            b1.ToTable("ticket_attachments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TicketId")
                                .HasConstraintName("fk_ticket_attachments_tickets_ticket_id");
                        });

                    b.OwnsMany("ServiceDesk.Tickets.Domain.TicketCategory", "Categories", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid")
                                .HasColumnName("category_id");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("NameSnapshot")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name_snapshot");

                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid")
                                .HasColumnName("ticket_id");

                            b1.Property<DateTime?>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at_utc");

                            b1.HasKey("Id")
                                .HasName("pk_ticket_categories");

                            b1.HasIndex(new[] { "TicketId", "CategoryId" }, "ix_ticket_categories_ticket_category")
                                .IsUnique()
                                .HasDatabaseName("ix_ticket_categories_ticket_id_category_id");

                            b1.ToTable("ticket_categories", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TicketId")
                                .HasConstraintName("fk_ticket_categories_tickets_ticket_id");
                        });

                    b.OwnsMany("ServiceDesk.Tickets.Domain.TicketComment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AuthorFullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("author_full_name");

                            b1.Property<Guid>("AuthorUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("author_user_id");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("body");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<bool>("IsEdited")
                                .HasColumnType("boolean")
                                .HasColumnName("is_edited");

                            b1.Property<Guid?>("ParentCommentId")
                                .HasColumnType("uuid")
                                .HasColumnName("parent_comment_id");

                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid")
                                .HasColumnName("ticket_id");

                            b1.Property<DateTime?>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at_utc");

                            b1.Property<int>("Visibility")
                                .HasColumnType("integer")
                                .HasColumnName("visibility");

                            b1.HasKey("Id")
                                .HasName("pk_ticket_comments");

                            b1.HasIndex(new[] { "TicketId" }, "ix_ticket_comments_ticket")
                                .HasDatabaseName("ix_ticket_comments_ticket_id");

                            b1.ToTable("ticket_comments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TicketId")
                                .HasConstraintName("fk_ticket_comments_tickets_ticket_id");
                        });

                    b.OwnsMany("ServiceDesk.Tickets.Domain.TicketStatusHistory", "StatusHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("ChangedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("changed_at_utc");

                            b1.Property<Guid?>("ChangedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("changed_by_user_id");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<int?>("FromStatus")
                                .HasColumnType("integer")
                                .HasColumnName("from_status");

                            b1.Property<string>("Note")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("note");

                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid")
                                .HasColumnName("ticket_id");

                            b1.Property<int>("ToStatus")
                                .HasColumnType("integer")
                                .HasColumnName("to_status");

                            b1.Property<DateTime?>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at_utc");

                            b1.HasKey("Id")
                                .HasName("pk_ticket_status_history");

                            b1.HasIndex(new[] { "TicketId" }, "ix_ticket_status_history_ticket")
                                .HasDatabaseName("ix_ticket_status_history_ticket_id");

                            b1.ToTable("ticket_status_history", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TicketId")
                                .HasConstraintName("fk_ticket_status_history_tickets_ticket_id");
                        });

                    b.Navigation("Assignees");

                    b.Navigation("Attachments");

                    b.Navigation("Categories");

                    b.Navigation("Comments");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("ServiceDesk.Tickets.Domain.TicketRating", b =>
                {
                    b.HasOne("ServiceDesk.Tickets.Domain.Ticket", null)
                        .WithOne("Rating")
                        .HasForeignKey("ServiceDesk.Tickets.Domain.TicketRating", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_ratings_tickets_ticket_id");
                });

            modelBuilder.Entity("ServiceDesk.Tickets.Domain.Ticket", b =>
                {
                    b.Navigation("Rating");
                });
#pragma warning restore 612, 618
        }
    }
}
